### PR TITLE
log panicking background threads

### LINKED ISSUE #1016: [DevOps] Panics currently don't trigger alerts.
When a background thread panics in our application, it does not currently trigger alerts with the panic. Instead we *may* get an alert that auctions are not being processed.

### PR DESCRIPTION
**Pull request by nlordell**
Fixes #1016 

This PR logs error messages for backgorund threads that panic so we get alerts in the alert channel. We use a panic hook, so this is done automatically for all background threads :tada: 

### Test Plan

Unit tests, add a `panic!("...")` line in the shadow orderbook and price source background threads and run the driver:
```
$ cargo run -p driver -- --use-shadowed-orderbook true --token-data '{ "T0001": { "alias": "WETH", "decimals": 18, "externalPrice": 200000000000000000000, "shouldEstimatePrice": true }}' --log-filter error
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/driver --use-shadowed-orderbook true --token-data '{ "T0001": { "alias": "WETH", "decimals": 18, "externalPrice": 200000000000000000000, "shouldEstimatePrice": true }}' --log-filter error`
   Compiling driver v0.1.0 (/var/home/nlordell/Developer/dex-services/driver)
    Finished dev [unoptimized + debuginfo] target(s) in 11.79s
     Running `target/debug/driver --use-shadowed-orderbook true --token-data '{ "T0001": { "alias": "WETH", "decimals": 18, "externalPrice": 200000000000000000000, "shouldEstimatePrice": true }}' --log-filter error`
2020-06-17T06:41:26.304Z ERRO [core::logging] thread '<unnamed>' panicked at 'hello shadow', core/src/orderbook/shadow_orderbook.rs:79:5
2020-06-17T06:41:26.304Z ERRO [core::logging] thread '<unnamed>' panicked at 'hello pricesource', core/src/price_estimation/threaded_price_source.rs:60:17
2020-06-17T06:41:26.305Z ERRO [core::logging] thread '<unnamed>' panicked at 'hello pricesource', core/src/price_estimation/threaded_price_source.rs:60:17
```

### CODE REVIEW

**Review by e00E — APPROVED** [review]
Looks good.

**Review by fleupold — APPROVED** [review]

**Comment by nlordell** [comment]
See discussion in #1016

**Comment by nlordell** [comment]
@fleupold I modified the code to use a custom panic hook that prints the panic to `log::error` instead of `STDERR`.

**Review by e00E — APPROVED** [review]
I like this more than manually doing it for every thread.

**Comment by fleupold** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2F3o7aTLkyh3yAG6DEuQ%2Fgiphy.gif&token=great" data-gitmeme-token="great"></a>

**Pull request merged**
