### PR TITLE
Update the default log filter after `core` name change

### PR DESCRIPTION
**Pull request by e00E**
I forgot this when changing the name of the core crate.

### CODE REVIEW

**Review by nlordell — COMMENTED** [review]
Can we use `module_path!` macro in `std`?

**Comment by e00E** [comment]
You mean instead of `driver` and `price-estimator`?

**Comment by nlordell** [comment]
> You mean instead of driver and price-estimator? It wouldn't help for services_core.

I mean we could define in `services-core/src/logging.rs` we could:
```
    pub const DEFAULT_FILTER: &str = concat!("warn,", module_path!(), "=info");
```

And then in price estimator and driver:
```
default_value = concat!(logging::DEFAULT_FILTER, "driver=info")
```

**Review by nlordell — APPROVED** [review]
Now that I think about it a bit more, I don't think my suggestion is worth implementing.

**Review by fleupold — APPROVED** [review]

**Pull request merged**
