### PR TITLE
Allow hardcoded token info

### PR DESCRIPTION
**Pull request by e00E**
Used as an override to the ERC20 information we fetch from the block chain
in case that information is wrong or unavailable which can happen for
example when tokens do not implement the standard properly.

### Test Plan
Manually tested with `'{69:{"alias":"aaa","decimals":1,"externalPrice":2,}}'` and checked that the info is overriden.

### CODE REVIEW

**Review by nlordell — APPROVED** [review]
Easy

**Review by fleupold — APPROVED** [review]
Nice! I don't think we need it right now but will be good to have if we need it later. Just a shame that this list will likely have to be duplicated in the config. I'm wondering if we should instead make it part of the code repo?

**Comment by e00E** [comment]
We should merge this anyway in case we need it. Kubernetes might allow us to share parts of the config in a way that makes this possible. It feels wrong to have hard coded constants that only match one specific deployment of the smart contract.

**Comment by nlordell** [comment]
>  I'm wondering if we should instead make it part of the code repo?

One of the main advantages of having it as a command line argument is that we can quickly modify the value and restart the pod in case of any issues.

What we could do, is implement a `TokenData::default_for_network(network_id: impl AsRef<str>)` so we have some hard coded default values in the future when the need arises. For now I also prefer having this in our pocket in case we have some issues with a specific token.

**Pull request merged**
