### PR TITLE
[StableX] Integrate Linear Optimization solver

### PR DESCRIPTION
**Pull request by fleupold**
This PR integrates the stableX driver with Tom's solver. For that we upgrade the solver to v0.2 and build support for the fee mechanism in the rust component.

Another change that was necessary is to remove passing the previous prices (since this list can potentially become extremely long). We will have to implement support for these going forward, but it seems like something that should be tackled separately. I will create a task for it.

As a nice side effect the price finding component no longer needs to be mutable.

### Follow Up Issues

- https://github.com/gnosis/dex-services/issues/258
- https://github.com/gnosis/dex-services/issues/260

### Test Plan

```
docker-compose build --build-arg use_solver=1 stablex
docker-compose down && docker-compose up stablex
```

In another terminal:

```
cd dex-contracts/
npx truffle migrate
npx truffle exec scripts/stablex/setup_environment.js

npx truffle exec scripts/stablex/deposit.js --accountId=0 --tokenId=0 --amount=3000
npx truffle exec scripts/stablex/deposit.js --accountId=1 --tokenId=1 --amount=3000

npx truffle exec scripts/stablex/place_order.js --accountId=0 --buyToken=1 --sellToken=0 --minBuy=100 --maxSell=2000 --validFor=20
npx truffle exec scripts/stablex/place_order.js --accountId=1 --buyToken=0 --sellToken=1 --minBuy=100 --maxSell=1000 --validFor=20

npx truffle exec scripts/wait_seconds.js 300
```

And see how the linear solver finds a reasonable solution.

### CODE REVIEW

**Comment by bh2smith** [comment]
The second deposit is duplicated in the test plan!

> npx truffle exec scripts/stablex/deposit.js --accountId=0 --tokenId=0 --amount=3000

It yields a very strange warning of:

```
> Warning: possible unsupported (undocumented in help) command line option: --accountId=0,--tokenId=0,--amount=3000
Using network 'development'.

Error: Returned error: VM Exception while processing transaction: revert
    at Object.ErrorResponse (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/~/web3-core-helpers/src/errors.js:29:1)
    at /Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:140:1
    at /Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:96:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/Users/admin/Projects/gnosis/dex-services/dex-contracts/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Truffle v5.0.26 (core: 5.0.26)
Node v12.8.0
```

**Comment by fleupold** [comment]
> The second deposit is duplicated in the test plan!

Good catch. Updated it

**Comment by bh2smith** [comment]
It appears the `stablex` container has an error with Constraint 'cons_max_executable_orders` (but this looks like a python error). 

I guess it would be nice if we could catch these exceptions somehow and handle them nicely!

How often is the solver looking for solutions? I feel like I was getting the `ValueError` much more often than an auction should actually occur. Perhaps it also wouldn't hurt to start including a timestamp in our logs...

**Comment by bh2smith** [comment]
I am a little worried about that duplicated deposit. I assume the problem was an insufficient balance, and would expect that I would be informed of such a fact when this is the case.

**Pull request merged**
