### PR TITLE
[Listener] Write init constants to DB

### PR DESCRIPTION
**Pull request by fleupold**
As title. This PR also updates the contracts to use the most recent version.

### Test plan:
```
git submodule update
cd dex-contracts
rm -r build
truffle build
cd ../
docker-compose build truffle
docker-compose up
```

Open localhost:3000 in a browser and see that constants table has new entries.

### CODE REVIEW

**Comment by bh2smith** [comment]
There appears to be a driver error here.

```
driver_1       |    Compiling driver v0.1.0 (/app/driver)
driver_1       | error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
driver_1       |  --> src/lib.rs:5:1
driver_1       |   |
driver_1       | 5 | extern crate log;
driver_1       |   | ^^^^^^^^^^^^^^^^^
driver_1       | 
driver_1       | error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
driver_1       |   --> src/lib.rs:37:9
driver_1       |    |
driver_1       | 37 |         error!("Deposit_driver error: {}", e);
driver_1       |    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
driver_1       |    |
driver_1       |    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
driver_1       |
```

**Comment by bh2smith** [comment]
Also found a listener error

```
listener_1     | 2019-06-06 15:06:00,814 [WARNING] [MainProcess] Unhandled Event: OwnershipTransferred
listener_1     | 2019-06-06 15:06:00,815 [INFO] [MainProcess] SnappInitialization received {'stateHash': '0000000000000000000000000000000000000000000000000000000000000000', 'maxTokens': 30, 'maxAccounts': 100}
listener_1     | 2019-06-06 15:06:00,849 [INFO] [MainProcess] Successfully included Snapp Initialization constants and account record
listener_1     | 2019-06-06 15:06:00,851 [INFO] [MainProcess] AuctionInitialization received {'maxOrders': 1000}
listener_1     | Traceback (most recent call last):
listener_1     |   File "manage.py", line 15, in <module>
listener_1     |     execute_from_command_line(sys.argv)
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
listener_1     |     utility.execute()
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
listener_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
listener_1     |     self.execute(*args, **cmd_options)
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
listener_1     |     output = self.handle(*args, **options)
listener_1     |   File "/app/event_listener/dfusion_db/management/commands/run_listener.py", line 16, in handle
listener_1     |     event_listener.execute()
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django_eth_events/event_listener.py", line 430, in execute
listener_1     |     contract_address_cache)
listener_1     |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
listener_1     |     return func(*args, **kwds)
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django_eth_events/event_listener.py", line 472, in process_block
listener_1     |     instance = self.save_event(contract, log, current_block)
listener_1     |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
listener_1     |     return func(*args, **kwds)
listener_1     |   File "/usr/local/lib/python3.6/site-packages/django_eth_events/event_listener.py", line 163, in save_event
listener_1     |     return event_receiver.save(decoded_event=decoded_log, block_info=block_info)
listener_1     |   File "/app/event_listener/dfusion_db/generic_event_receiver.py", line 38, in save
listener_1     |     listener.save(parsed_event, block_info)
listener_1     |   File "/app/event_listener/dfusion_db/snapp_event_receiver.py", line 121, in save
listener_1     |     assert event.keys() == {'maxOrders', 'numReservedAccounts', 'ordersPerReservedAccount'}, "Unexpected Event Keys"
listener_1     | AssertionError: Unexpected Event Keys
```

**Comment by fleupold** [comment]
@bh2smith did you try `git submodule update` and it did not work?

**Comment by fleupold** [comment]
As title. This PR also updates the contracts to use the most recent version.

Test plan:
git submodule update
cd dex-contracts
rm -r build
truffle build
cd ../
docker-compose build truffle
docker-compose up
Open localhost:3000 in a browser and see that constants table has new entries.

**Comment by bh2smith** [comment]
@fleupold Yes, I did try that and it didn't work. I can try again next time.

**Pull request merged**
