### PR TITLE
Using the pricegraph based price source

### PR DESCRIPTION
**Pull request by fleupold**
Another part of #842 

Wiring the PriceSource implemented into the PriceOracle. Thanks to @bh2smith we have a generalized price averager so it blends in perfectly

### Test Plan
Locally added a log statement [here](https://github.com/gnosis/dex-services/blob/6c707afc5810175514e3e152e075446cc6d47262/core/src/price_estimation/average_price_source.rs#L60) and checked the prices that come from the different estimators.

```
{ //Kraken
 TokenId(1): 237463200000000000000
 TokenId(17): 1731802277999999975424
 TokenId(18): 31145554000000000000}
 TokenId(2): 998999089999999938083831152640
 TokenId(4): 999993230000000014083789160448
 TokenId(7): 1002282010000000000
{ // Dex.AG
 TokenId(1): 230668323140797759488
 TokenId(11): 92432835763096017519446757212160
 TokenId(13): 204933911831484703327649792
 TokenId(15): 998937536173875456
 TokenId(16): 1018009467371560064
 TokenId(18): 29794731401406971904
 TokenId(2): 996815296265141614641498030080
 TokenId(3): 997787998047215744}
 TokenId(4): 998045855486907286071254450176
 TokenId(5): 990686005156938624
 TokenId(7): 1000000000000000000
 TokenId(8): 228279894624465879040
 TokenId(9): 998005984974353920
{ // Pricegraph
 TokenId(1): 331388496557023428608
 TokenId(13): 306061793460530986411360256
 TokenId(15): 1335277474577182976
 TokenId(16): 1506153881626714624
 TokenId(18): 70923235125248409600
 TokenId(2): 1418535629286432721762428911616
 TokenId(3): 1418535629286433024
 TokenId(4): 1418464702504968565999544565760
 TokenId(5): 1418535629286433024
 TokenId(6): 14186065631612846219912596399587328
 TokenId(7): 1417046237802463744
 TokenId(8): 330582114722813313024
 TokenId(9): 1418606563161284608
}
```

### CODE REVIEW

**Comment by nlordell** [comment]
> ```
> TokenId(2): 1418535629286432721762428911616
> TokenId(3): 1418535629286433024
> TokenId(4): 1418464702504968565999544565760
> TokenId(5): 1418535629286433024
> TokenId(6): 14186065631612846219912596399587328
> TokenId(7): 1417046237802463744
> ```

It’s pretty cool that the price estimates for USD stable coins all agree!

We also see with the pricegraph estimates that OWL is valued at less than a dollar on our exchange, I think this might help the solver as the prices might be a bit closer to the actual optimal.

**Review by nlordell — APPROVED** [review]
Nice to see it all coming together!

**Review by e00E — APPROVED** [review]

**Comment by fleupold** [comment]
I might hold off merging this until next Monday so that it can "bake" in staging for a week before going to prod. Or do you guys think otherwise?

**Comment by e00E** [comment]
It's probably a good idea to give the oncall less potential work on the weekend.

**Comment by nlordell** [comment]
> I might hold off merging this until next Monday so that it can "bake" in staging for a week before going to prod. Or do you guys think otherwise?

Yes, and there is #916 which might cause some alerts over the weekend which aren't nice to deal with.

**Review by bh2smith — APPROVED** [review]
Noice! Thanks for waiting for me to see this to merge! Looks great.

**Comment by twalth3r** [comment]
> do you guys think that these price estimates that value OWL lower than 1USD is helpful or detrimental to the solver?

Definitely helpful, since it reflects the price of OWL in the solution much better!

**Comment by fleupold** [comment]
Heads up, that I rewired the price source again. Instead of being 

- Threaded (background fetched)
  - Average
    - kraken
    - dex.AG
    - internal

It's now

- Average
  - Threaded
    - kraken
  - Threaded
    - dex.AG
  - internal

so that the internal source is not running on a background thread prior to when the data is actually needed (this is because otherwise our estimate could be based on an old batch that doesn't have certain valid orders yet).

This means we use one more thread overall.

**Comment by nlordell** [comment]
> It's now [...]

If you really wanted to be fancy, you could make it:

- Average
  - Threaded
    - Average
        - Kraken
        - DexAg
  - internal

Not sure if its worth it though.

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
I think we should be able to merge this now so that it runs for the week.

**Comment by fleupold** [comment]
> I think we should be able to merge this now so that it runs for the week.

I wanted to wait for the release to be cut (including the best ring solver fix). Will merge this tomorrow as soon as you tagged this weeks release version.

> If you really wanted to be fancy, you could make it:

Average(a, Average(b, c)) is not the same as Average(a,b,c) though.

**Comment by nlordell** [comment]
> Average(a, Average(b, c)) is not the same as Average(a,b,c) though.

:see_no_evil: Ooops!

**Pull request merged**
