### PR TITLE
#83 - Store all large integers in DB as string

### PR DESCRIPTION
**Pull request by bh2smith**
1. Event Listener to write Strings to DB for all "large integers" (i.e. > 64 bits). Only change required here is to update the `to_dictionary` function for each model (since these dictionaries are what is written to the DB). Its really nice that we don't have to change the model definitions!

2. Driver will have to implement a different `from` method as which parses these amounts as strings

### CODE REVIEW

**Comment by josojo** [comment]
Yes, this is the right direction to go!

**Comment by bh2smith** [comment]
Maybe one of @josojo  or @fleupold can help with this (not very descriptive) error I am getting with the current state of the code.

```
driver_1 | Querying stateHash: { "stateHash": "0000000000000000000000000000000000000000000000000000000000000000" }
driver_1 | Deposit_driver error: JSON error
driver_1 | Current top withdraw_slot is 1
driver_1 | Highest unprocessed withdraw_slot is 0
driver_1 | Processing withdraw_slot 0
driver_1 | Querying stateHash: { "stateHash": "0000000000000000000000000000000000000000000000000000000000000000" }
driver_1 | Withdraw_driver error: JSON error
```

Best I can tell is that this is coming from `get_current_balances`

**Comment by bh2smith** [comment]
@josojo & @fleupold. This is now working with e2e-tests and ready for review. Note that some parts have been taken from this other draft PR #80 (particularly the From implementations for the DB models).

**Comment by bh2smith** [comment]
@fleupold unfortunately it is not going to be so easy to fix this last failing test case. The reason for failure is that the Merkle Roots do not agree. This is actually a bug in the contracts repo with the JS implementation if `encodePacked_16_8_128`. I will open an issue in contracts that will need to be taken care of before this can ever pass!

**Pull request merged**
