### PR TITLE
Implement custom benign errors

### PR DESCRIPTION
**Pull request by nlordell**
This PR offers a simple work around to help silence benign errors on a per-configuration basis.

### Test Plan

Added unit test.

### CODE REVIEW

**Review by vkgnosis — APPROVED** [review]
I think that in our kibana alerts filter we could also filter per pod name to accomplish a similar thing but having this here probably more ergonomic.

**Comment by nlordell** [comment]
> I think that in our kibana alerts filter we could also filter per pod name to accomplish a similar thing but having this here probably more ergonomic.

I already installed a kibana filter, the issue is that it counts towards the Grafana metrics as a failed batch.

**Review by fleupold — APPROVED** [review]
>  it counts towards the Grafana metrics as a failed batch.

I would have said this is actually intended (since we are not finding a solution for those batches), but I see that we are already excluding subtraction underflows, so the same argument can apply for multiplication overflows.

**Comment by nlordell** [comment]
> I would have said this is actually intended (since we are not finding a solution for those batches),

The thing is we want to suppress the alerts for Rinkeby for multiplication overflows. Maybe for v2 we can have a separate category for this kind of failure?

**Pull request merged**
