### PR TITLE
[Easy] add github PR template

### PR DESCRIPTION
**Pull request by fleupold**
This will hopefully make it easier for us to make a good description and most importantly a test plan for PRs going forward. I Followed this tutorial: https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f

### Test Plan

I was hoping the template would already show up here, but I guess it has to be merged into master first. Will try to create a new PR with this template after merging.

### CODE REVIEW

**Review by nlordell — APPROVED** [review]
Sweet! I like how this incentivizes the creation of issues for PRs (something that I admittedly am very bad at).

Maybe we can create one for issues as well.

**Comment by nlordell** [comment]
*Requested Change*: Missing issue in PR description
:rofl:

**Comment by fleupold** [comment]
I'm not a big fan of creating an issue for small tasks (e.g. if it takes the same time to create the PR that fixes the thing instead). 
I can make it more explicit that the issue reference is optional.

**Review by e00E — APPROVED** [review]

**Review by josojo — COMMENTED** [review]
Like it

**Review by bh2smith — APPROVED** [review]

**Pull request merged**
