### PR TITLE
Remove reference to dfusion_rust_core folder

### PR DESCRIPTION
**Pull request by e00E**

### CODE REVIEW

**Comment by fleupold** [comment]
Should we review this?

**Comment by e00E** [comment]
I needed this locally or some container wouldn't build because the folder is missing. Then I saw at least one of those changes in a different PR so I decided to wait and see if its still needed. I marked it as a "Draft" to show that it doesn't need to be reviewed yet.

**Comment by e00E** [comment]
I am going to rebase master and if CI succeeds mark it for review.

**Comment by nlordell** [comment]
@e00E I think this can be closed as those lines were removed with the refactoring of `driver` crate from lib to bin.

**Pull request closed without merging**
